version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Istanbul

volumes:
  postgres_data:
  